name: Daily Markets Report

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install uv
      run: pip install uv
        
    - name: Install dependencies
      run: uv pip install --system openai python-dotenv yfinance pycoingecko requests jinja2 markdown
      
    - name: Debug file structure
      working-directory: ./src
      run: |
        echo "=== Working directory ==="
        pwd
        echo ""
        echo "=== Files in current directory ==="
        ls -la
        echo ""
        echo "=== Check templates folder ==="
        if [ -d "templates" ]; then
          echo "templates/ exists!"
          ls -la templates/
        else
          echo "templates/ NOT FOUND"
        fi
        echo ""
        echo "=== Check for template file ==="
        if [ -f "templates/daily_report.html" ]; then
          echo "daily_report.html EXISTS"
        else
          echo "daily_report.html NOT FOUND"
        fi
      
    - name: Generate report
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      working-directory: ./src
      run: python main.py
    
    - name: Check what was generated
      run: |
        echo "=== Reports directory ==="
        if [ -d "src/reports" ]; then
          ls -la src/reports/
        else
          echo "src/reports/ does not exist!"
        fi
      
    - name: Commit and push report
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/reports/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Daily report $(date +'%Y-%m-%d')" && git push)